### PR TITLE
fix: generate es modules instead of commonjs for npm packages

### LINKED ISSUE #35: npm module type mismatch
When trying to import the generated npm package to [shortt](https://github.com/nathanfallet/shortt), it does not work when running the web app (even though there is no visible error in the IDE):

```
SyntaxError: Importing binding name 'LoginResponseSchema' is not found.
```

The way I solved it was by changing those things:

1. backend/api/build/zodable/package.json:12 - Changed "type": "commonjs" to "type": "module"
2. backend/api/build/zodable/tsconfig.json:29 - Changed "module": "commonjs" to "module": "ES2020"
3. backend/api/build/zodable/tsconfig.json:31 - Enabled "moduleResolution": "node"
4. Recompiled TypeScript to generate ES module syntax (export const instead of exports.)
5. Reinstalled workspace dependencies

So I'm asking myself:
- Why there is this commonjs/module(esxxxx) distinction?
- It was working in the previous React (web+native) app, so if we change the generated package type will it break?

A good solution would be for zodable to either:

1. Default to ES modules (since they work in more environments)
2. Make it configurable via a zodable setting
3. Support both formats by generating dual packages (though this is complex)

### PR DESCRIPTION
**Pull request by nathanfallet**
Fixes #35

### CODE REVIEW

File: zodable-gradle-plugin/src/main/kotlin/digital/guimauve/zodable/ZodablePlugin.kt [hunk 1]
```diff
@@ -152,6 +153,8 @@ abstract class ZodablePlugin : Plugin<Project> {
                             listOf(
                                 "npx", "tsc", "--init",
                                 "-d",
+                                "--module", "ES2020",
+                                "--moduleResolution", "node",
```
Comment (rocketraman) [inline zodable-gradle-plugin/src/main/kotlin/digital/guimauve/zodable/ZodablePlugin.kt]: Typescript docs indicate this should not be used for new projects (https://www.typescriptlang.org/docs/handbook/modules/reference.html#node10-formerly-known-as-node).

I would imagine `bundler` might be more appropriate for code that is going to target RN or the web?

Also note this from the docs:

> --moduleResolution bundler must be paired with --module esnext or --module preserve.
